server:
  port: ${random.int[8320,8330]}
spring:
  application:
    name: spring-cloud-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-agent-address: true
